import type { GlossaryEntry } from "./index.js";

export type GlossaryCategory =
  | "programming"
  | "technical"
  | "business"
  | "general"
  | "web"
  | "security"
  | "ai"
  | "localization"
  | "devops"
  | "database"
  | "mobile"
  | "networking";

export const GLOSSARY_CATEGORIES: GlossaryCategory[] = [
  "programming",
  "technical",
  "business",
  "general",
  "web",
  "security",
  "ai",
  "localization",
  "devops",
  "database",
  "mobile",
  "networking",
];

const SOURCE_BY_CATEGORY: Record<string, { source: string; sourceUrl: string }> = {
  programming: {
    source: "MDN Web Docs Glossary",
    sourceUrl: "https://developer.mozilla.org/en-US/docs/Glossary",
  },
  technical: {
    source: "Microsoft Language Portal",
    sourceUrl: "https://www.microsoft.com/language",
  },
  business: {
    source: "Microsoft Language Portal",
    sourceUrl: "https://www.microsoft.com/language",
  },
  general: {
    source: "Microsoft Language Portal",
    sourceUrl: "https://www.microsoft.com/language",
  },
  devops: {
    source: "CNCF Glossary",
    sourceUrl: "https://glossary.cncf.io/",
  },
  database: {
    source: "Oracle Database Documentation",
    sourceUrl: "https://docs.oracle.com/en/database/",
  },
  mobile: {
    source: "Apple Developer Documentation",
    sourceUrl: "https://developer.apple.com/documentation/",
  },
  networking: {
    source: "Cisco Networking Academy",
    sourceUrl: "https://www.netacad.com/",
  },
  web: {
    source: "MDN Web Docs Glossary",
    sourceUrl: "https://developer.mozilla.org/en-US/docs/Glossary",
  },
  security: {
    source: "OWASP Glossary and OWASP LLM Top 10",
    sourceUrl: "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
  },
  ai: {
    source: "NIST AI Risk Management Framework Glossary",
    sourceUrl: "https://www.nist.gov/itl/ai-risk-management-framework",
  },
  localization: {
    source: "W3C Internationalization and Unicode CLDR",
    sourceUrl: "https://www.w3.org/International/",
  },
};

const RAW_GLOSSARY_DATA: GlossaryEntry[] = [
  { term: "algorithm", translation: "algoritmo", category: "programming" },
  { term: "array", translation: "arreglo", category: "programming" },
  { term: "bug", translation: "error", category: "programming" },
  { term: "class", translation: "clase", category: "programming" },
  { term: "code", translation: "código", category: "programming" },
  { term: "compile", translation: "compilar", category: "programming" },
  { term: "compiler", translation: "compilador", category: "programming" },
  { term: "constant", translation: "constante", category: "programming" },
  { term: "debug", translation: "depurar", category: "programming" },
  { term: "debugger", translation: "depurador", category: "programming" },
  { term: "deployment", translation: "despliegue", category: "programming" },
  { term: "error", translation: "error", category: "programming" },
  { term: "exception", translation: "excepción", category: "programming" },
  { term: "function", translation: "función", category: "programming" },
  { term: "interface", translation: "interfaz", category: "programming" },
  { term: "library", translation: "biblioteca", category: "programming" },
  { term: "library", translation: "librería", category: "programming" },
  { term: "loop", translation: "bucle", category: "programming" },
  { term: "method", translation: "método", category: "programming" },
  { term: "object", translation: "objeto", category: "programming" },
  { term: "parameter", translation: "parámetro", category: "programming" },
  { term: "pointer", translation: "puntero", category: "programming" },
  { term: "program", translation: "programa", category: "programming" },
  { term: "programming", translation: "programación", category: "programming" },
  { term: "runtime", translation: "tiempo de ejecución", category: "programming" },
  { term: "software", translation: "software", category: "programming" },
  { term: "statement", translation: "sentencia", category: "programming" },
  { term: "string", translation: "cadena", category: "programming" },
  { term: "string", translation: "cadena de texto", category: "programming" },
  { term: "syntax", translation: "sintaxis", category: "programming" },
  { term: "variable", translation: "variable", category: "programming" },
  { term: "API", translation: "API", category: "technical" },
  { term: "application", translation: "aplicación", category: "technical" },
  { term: "bandwidth", translation: "ancho de banda", category: "technical" },
  { term: "browser", translation: "navegador", category: "technical" },
  { term: "cache", translation: "caché", category: "technical" },
  { term: "cloud", translation: "nube", category: "technical" },
  { term: "computer", translation: "computador", category: "technical" },
  { term: "computer", translation: "computadora", category: "technical" },
  { term: "computer", translation: "ordenador", category: "technical" },
  { term: "data", translation: "datos", category: "technical" },
  { term: "database", translation: "base de datos", category: "technical" },
  { term: "debugging", translation: "depuración", category: "technical" },
  { term: "development", translation: "desarrollo", category: "technical" },
  { term: "device", translation: "dispositivo", category: "technical" },
  { term: "directory", translation: "directorio", category: "technical" },
  { term: "directory", translation: "carpeta", category: "technical" },
  { term: "domain", translation: "dominio", category: "technical" },
  { term: "email", translation: "correo electrónico", category: "technical" },
  { term: "endpoint", translation: "punto de conexión", category: "technical" },
  { term: "file", translation: "archivo", category: "technical" },
  { term: "file", translation: "fichero", category: "technical" },
  { term: "filesystem", translation: "sistema de archivos", category: "technical" },
  { term: "framework", translation: "marco de trabajo", category: "technical", confidence: "low" },
  { term: "framework", translation: "framework", category: "technical" },
  { term: "hardware", translation: "hardware", category: "technical" },
  { term: "host", translation: "servidor", category: "technical" },
  { term: "host", translation: "host", category: "technical" },
  { term: "HTTP", translation: "HTTP", category: "technical" },
  { term: "HTTPS", translation: "HTTPS", category: "technical" },
  { term: "interface", translation: "interfaz", category: "technical" },
  { term: "IP address", translation: "dirección IP", category: "technical" },
  { term: "keyboard", translation: "teclado", category: "technical" },
  { term: "latency", translation: "latencia", category: "technical" },
  { term: "memory", translation: "memoria", category: "technical" },
  { term: "monitor", translation: "monitor", category: "technical" },
  { term: "mouse", translation: "ratón", category: "technical" },
  { term: "mouse", translation: "mouse", category: "technical" },
  { term: "network", translation: "red", category: "technical" },
  { term: "operating system", translation: "sistema operativo", category: "technical" },
  { term: "password", translation: "contraseña", category: "technical" },
  { term: "path", translation: "ruta", category: "technical" },
  { term: "path", translation: "camino", category: "technical" },
  { term: "processor", translation: "procesador", category: "technical" },
  { term: "protocol", translation: "protocolo", category: "technical" },
  { term: "repository", translation: "repositorio", category: "technical" },
  { term: "response time", translation: "tiempo de respuesta", category: "technical" },
  { term: "screen", translation: "pantalla", category: "technical" },
  { term: "server", translation: "servidor", category: "technical" },
  { term: "software", translation: "software", category: "technical" },
  { term: "URL", translation: "URL", category: "technical" },
  { term: "username", translation: "nombre de usuario", category: "technical" },
  { term: "web", translation: "web", category: "technical" },
  { term: "website", translation: "sitio web", category: "technical" },
  { term: "WiFi", translation: "WiFi", category: "technical" },
  { term: "account", translation: "cuenta", category: "business" },
  { term: "budget", translation: "presupuesto", category: "business" },
  { term: "business", translation: "negocio", category: "business" },
  { term: "client", translation: "cliente", category: "business" },
  { term: "company", translation: "empresa", category: "business" },
  { term: "contract", translation: "contrato", category: "business" },
  { term: "cost", translation: "costo", category: "business" },
  { term: "customer", translation: "cliente", category: "business" },
  { term: "deadline", translation: "fecha límite", category: "business" },
  { term: "discount", translation: "descuento", category: "business" },
  { term: "employee", translation: "empleado", category: "business" },
  { term: "employer", translation: "empleador", category: "business" },
  { term: "expense", translation: "gasto", category: "business" },
  { term: "income", translation: "ingreso", category: "business" },
  { term: "invoice", translation: "factura", category: "business" },
  { term: "manager", translation: "gerente", category: "business" },
  { term: "meeting", translation: "reunión", category: "business" },
  { term: "offer", translation: "oferta", category: "business" },
  { term: "payment", translation: "pago", category: "business" },
  { term: "price", translation: "precio", category: "business" },
  { term: "profit", translation: "ganancia", category: "business" },
  { term: "profit", translation: "beneficio", category: "business" },
  { term: "project", translation: "proyecto", category: "business" },
  { term: "receipt", translation: "recibo", category: "business" },
  { term: "report", translation: "informe", category: "business" },
  { term: "revenue", translation: "ingreso", category: "business" },
  { term: "salary", translation: "salario", category: "business" },
  { term: "sales", translation: "ventas", category: "business" },
  { term: "service", translation: "servicio", category: "business" },
  { term: "stakeholder", translation: "interesado", category: "business" },
  { term: "supplier", translation: "proveedor", category: "business" },
  { term: "team", translation: "equipo", category: "business" },
  { term: "user", translation: "usuario", category: "business" },
  { term: "access", translation: "acceso", category: "general" },
  { term: "action", translation: "acción", category: "general" },
  { term: "change", translation: "cambio", category: "general" },
  { term: "click", translation: "clic", category: "general" },
  { term: "configuration", translation: "configuración", category: "general" },
  { term: "content", translation: "contenido", category: "general" },
  { term: "date", translation: "fecha", category: "general" },
  { term: "description", translation: "descripción", category: "general" },
  { term: "download", translation: "descargar", category: "general" },
  { term: "error", translation: "error", category: "general" },  // also in programming
  { term: "feature", translation: "característica", category: "general" },
  { term: "feature", translation: "funcionalidad", category: "general" },
  { term: "help", translation: "ayuda", category: "general" },
  { term: "language", translation: "idioma", category: "general" },
  { term: "language", translation: "lenguaje", category: "general" },
  { term: "link", translation: "enlace", category: "general" },
  { term: "login", translation: "iniciar sesión", category: "general" },
  { term: "logout", translation: "cerrar sesión", category: "general" },
  { term: "message", translation: "mensaje", category: "general" },
  { term: "name", translation: "nombre", category: "general" },
  { term: "option", translation: "opción", category: "general" },
  { term: "page", translation: "página", category: "general" },
  { term: "password", translation: "contraseña", category: "general" },
  { term: "search", translation: "búsqueda", category: "general" },
  { term: "search", translation: "buscar", category: "general" },
  { term: "setting", translation: "configuración", category: "general" },
  { term: "setting", translation: "ajuste", category: "general" },
  { term: "status", translation: "estado", category: "general" },
  { term: "status", translation: "estatus", category: "general" },
  { term: "success", translation: "éxito", category: "general" },
  { term: "support", translation: "soporte", category: "general" },
  { term: "text", translation: "texto", category: "general" },
  { term: "title", translation: "título", category: "general" },
  { term: "update", translation: "actualización", category: "general" },
  { term: "update", translation: "actualizar", category: "general" },
  { term: "user", translation: "usuario", category: "general" },
  { term: "value", translation: "valor", category: "general" },
  { term: "version", translation: "versión", category: "general" },
  { term: "view", translation: "vista", category: "general" },
  { term: "view", translation: "ver", category: "general" },
  { term: "warning", translation: "advertencia", category: "general" },
  { term: "abstract class", translation: "clase abstracta", category: "programming" },
  { term: "access modifier", translation: "modificador de acceso", category: "programming" },
  { term: "argument", translation: "argumento", category: "programming" },
  { term: "asynchronous", translation: "asíncrono", category: "programming" },
  { term: "callback", translation: "función de retorno", category: "programming" },
  { term: "constructor", translation: "constructor", category: "programming" },
  { term: "dependency", translation: "dependencia", category: "programming" },
  { term: "enum", translation: "enumeración", category: "programming" },
  { term: "generic", translation: "genérico", category: "programming" },
  { term: "immutable", translation: "inmutable", category: "programming" },
  { term: "inheritance", translation: "herencia", category: "programming" },
  { term: "iterator", translation: "iterador", category: "programming" },
  { term: "literal", translation: "literal", category: "programming" },
  { term: "namespace", translation: "espacio de nombres", category: "programming" },
  { term: "package", translation: "paquete", category: "programming" },
  { term: "promise", translation: "promesa", category: "programming" },
  { term: "recursion", translation: "recursión", category: "programming" },
  { term: "reference", translation: "referencia", category: "programming" },
  { term: "repository branch", translation: "rama de repositorio", category: "programming" },
  { term: "type inference", translation: "inferencia de tipos", category: "programming" },
  { term: "unit test", translation: "prueba unitaria", category: "programming" },
  { term: "integration test", translation: "prueba de integración", category: "programming" },
  { term: "end-to-end test", translation: "prueba de extremo a extremo", category: "programming" },
  { term: "test fixture", translation: "fixture de prueba", category: "programming" },
  { term: "regression test", translation: "prueba de regresión", category: "programming" },
  { term: "accessibility", translation: "accesibilidad", category: "web" },
  { term: "attribute", translation: "atributo", category: "web" },
  { term: "cookie", translation: "cookie", category: "web" },
  { term: "cross-origin", translation: "origen cruzado", category: "web" },
  { term: "document object model", translation: "modelo de objetos del documento", category: "web" },
  { term: "event handler", translation: "controlador de eventos", category: "web" },
  { term: "form field", translation: "campo de formulario", category: "web" },
  { term: "heading", translation: "encabezado", category: "web" },
  { term: "hyperlink", translation: "hipervínculo", category: "web" },
  { term: "iframe", translation: "iframe", category: "web" },
  { term: "local storage", translation: "almacenamiento local", category: "web" },
  { term: "media query", translation: "consulta de medios", category: "web" },
  { term: "responsive design", translation: "diseño adaptable", category: "web" },
  { term: "screen reader", translation: "lector de pantalla", category: "web" },
  { term: "service worker", translation: "service worker", category: "web" },
  { term: "session storage", translation: "almacenamiento de sesión", category: "web" },
  { term: "single-page application", translation: "aplicación de página única", category: "web" },
  { term: "style sheet", translation: "hoja de estilos", category: "web" },
  { term: "web component", translation: "componente web", category: "web" },
  { term: "websocket", translation: "WebSocket", category: "web" },
  { term: "acceptance criteria", translation: "criterios de aceptación", category: "business" },
  { term: "backlog", translation: "lista de pendientes", category: "business" },
  { term: "billing", translation: "facturación", category: "business" },
  { term: "churn", translation: "abandono", category: "business" },
  { term: "conversion rate", translation: "tasa de conversión", category: "business" },
  { term: "deliverable", translation: "entregable", category: "business" },
  { term: "go-to-market", translation: "salida al mercado", category: "business" },
  { term: "key performance indicator", translation: "indicador clave de rendimiento", category: "business" },
  { term: "milestone", translation: "hito", category: "business" },
  { term: "onboarding", translation: "incorporación", category: "business" },
  { term: "roadmap", translation: "hoja de ruta", category: "business" },
  { term: "scope", translation: "alcance", category: "business" },
  { term: "service-level agreement", translation: "acuerdo de nivel de servicio", category: "business" },
  { term: "subscription", translation: "suscripción", category: "business" },
  { term: "user story", translation: "historia de usuario", category: "business" },
  { term: "authentication token", translation: "token de autenticación", category: "security" },
  { term: "authorization header", translation: "cabecera de autorización", category: "security" },
  { term: "certificate", translation: "certificado", category: "security" },
  { term: "cross-site scripting", translation: "secuencias de comandos entre sitios", category: "security" },
  { term: "cross-site request forgery", translation: "falsificación de petición en sitios cruzados", category: "security" },
  { term: "denial of service", translation: "denegación de servicio", category: "security" },
  { term: "encryption key", translation: "clave de cifrado", category: "security" },
  { term: "hash function", translation: "función hash", category: "security" },
  { term: "least privilege", translation: "mínimo privilegio", category: "security" },
  { term: "malware", translation: "software malicioso", category: "security" },
  { term: "multi-factor authentication", translation: "autenticación multifactor", category: "security" },
  { term: "password manager", translation: "gestor de contraseñas", category: "security" },
  { term: "penetration test", translation: "prueba de penetración", category: "security" },
  { term: "prompt injection", translation: "inyección de instrucciones", category: "security" },
  { term: "rate limit", translation: "límite de tasa", category: "security" },
  { term: "secret scanning", translation: "escaneo de secretos", category: "security" },
  { term: "security policy", translation: "política de seguridad", category: "security" },
  { term: "server-side request forgery", translation: "falsificación de solicitudes del lado del servidor", category: "security" },
  { term: "threat model", translation: "modelo de amenazas", category: "security" },
  { term: "zero trust", translation: "confianza cero", category: "security" },
  { term: "alignment", translation: "alineación", category: "ai" },
  { term: "artificial intelligence", translation: "inteligencia artificial", category: "ai" },
  { term: "attention mechanism", translation: "mecanismo de atención", category: "ai" },
  { term: "benchmark", translation: "banco de pruebas", category: "ai" },
  { term: "classification", translation: "clasificación", category: "ai" },
  { term: "context window", translation: "ventana de contexto", category: "ai" },
  { term: "embedding", translation: "incrustación", category: "ai" },
  { term: "evaluation", translation: "evaluación", category: "ai" },
  { term: "fine-tuning", translation: "ajuste fino", category: "ai" },
  { term: "foundation model", translation: "modelo fundacional", category: "ai" },
  { term: "generative model", translation: "modelo generativo", category: "ai" },
  { term: "hallucination", translation: "alucinación", category: "ai" },
  { term: "inference", translation: "inferencia", category: "ai" },
  { term: "large language model", translation: "modelo de lenguaje grande", category: "ai" },
  { term: "model context protocol", translation: "protocolo de contexto de modelo", category: "ai" },
  { term: "model weights", translation: "pesos del modelo", category: "ai" },
  { term: "prompt", translation: "instrucción", category: "ai" },
  { term: "reinforcement learning", translation: "aprendizaje por refuerzo", category: "ai" },
  { term: "retrieval augmented generation", translation: "generación aumentada por recuperación", category: "ai" },
  { term: "system prompt", translation: "instrucción del sistema", category: "ai" },
  { term: "temperature", translation: "temperatura", category: "ai" },
  { term: "token", translation: "token", category: "ai" },
  { term: "training data", translation: "datos de entrenamiento", category: "ai" },
  { term: "transformer", translation: "transformador", category: "ai" },
  { term: "vector database", translation: "base de datos vectorial", category: "ai" },
  { term: "back translation", translation: "retrotraducción", category: "localization" },
  { term: "bidirectional text", translation: "texto bidireccional", category: "localization" },
  { term: "character encoding", translation: "codificación de caracteres", category: "localization" },
  { term: "collation", translation: "ordenación", category: "localization" },
  { term: "content adaptation", translation: "adaptación de contenido", category: "localization" },
  { term: "date format", translation: "formato de fecha", category: "localization" },
  { term: "dialect adaptation", translation: "adaptación dialectal", category: "localization" },
  { term: "fallback locale", translation: "configuración regional alternativa", category: "localization" },
  { term: "gender-neutral language", translation: "lenguaje inclusivo", category: "localization" },
  { term: "glossary term", translation: "término de glosario", category: "localization" },
  { term: "internationalization", translation: "internacionalización", category: "localization" },
  { term: "language tag", translation: "etiqueta de idioma", category: "localization" },
  { term: "locale", translation: "configuración regional", category: "localization" },
  { term: "localization", translation: "localización", category: "localization" },
  { term: "machine translation", translation: "traducción automática", category: "localization" },
  { term: "message catalog", translation: "catálogo de mensajes", category: "localization" },
  { term: "number format", translation: "formato numérico", category: "localization" },
  { term: "plural rule", translation: "regla de plural", category: "localization" },
  { term: "protected term", translation: "término protegido", category: "localization" },
  { term: "quality estimation", translation: "estimación de calidad", category: "localization" },
  { term: "regional variant", translation: "variante regional", category: "localization" },
  { term: "source string", translation: "cadena de origen", category: "localization" },
  { term: "target locale", translation: "configuración regional de destino", category: "localization" },
  { term: "term base", translation: "base terminológica", category: "localization" },
  { term: "translation memory", translation: "memoria de traducción", category: "localization" },
  { term: "translatable string", translation: "cadena traducible", category: "localization" },
  { term: "unicode normalization", translation: "normalización Unicode", category: "localization" },
  { term: "account settings", translation: "configuración de la cuenta", category: "general" },
  { term: "activity log", translation: "registro de actividad", category: "general" },
  { term: "alert", translation: "alerta", category: "general" },
  { term: "attachment", translation: "archivo adjunto", category: "general" },
  { term: "confirmation", translation: "confirmación", category: "general" },
  { term: "dashboard", translation: "panel de control", category: "general" },
  { term: "default setting", translation: "configuración predeterminada", category: "general" },
  { term: "notification", translation: "notificación", category: "general" },
  { term: "permission", translation: "permiso", category: "general" },
  { term: "preference", translation: "preferencia", category: "general" },
  { term: "profile", translation: "perfil", category: "general" },
  { term: "shortcut", translation: "atajo", category: "general" },
  { term: "sync", translation: "sincronizar", category: "general" },
  { term: "template", translation: "plantilla", category: "general" },
  { term: "workspace", translation: "espacio de trabajo", category: "general" },

  // --- devops ---
  { term: "container", translation: "contenedor", category: "devops" },
  { term: "orchestration", translation: "orquestación", category: "devops" },
  { term: "pipeline", translation: "pipeline", category: "devops" },
  { term: "CI/CD", translation: "CI/CD (integración y entrega continua)", category: "devops" },
  { term: "deployment", translation: "despliegue", category: "devops" },
  { term: "staging environment", translation: "entorno de pruebas", category: "devops" },
  { term: "production environment", translation: "entorno de producción", category: "devops" },
  { term: "monitoring", translation: "monitoreo", category: "devops" },
  { term: "alerting", translation: "alertas", category: "devops" },
  { term: "incident", translation: "incidente", category: "devops" },
  { term: "post-mortem", translation: "post-mortem", category: "devops" },
  { term: "rollback", translation: "reversión", category: "devops" },
  { term: "canary deployment", translation: "despliegue canario", category: "devops" },
  { term: "blue-green deployment", translation: "despliegue azul-verde", category: "devops" },
  { term: "infrastructure as code", translation: "infraestructura como código", category: "devops" },
  { term: "load balancer", translation: "balanceador de carga", category: "devops" },
  { term: "scalability", translation: "escalabilidad", category: "devops" },
  { term: "uptime", translation: "tiempo de actividad", category: "devops" },
  { term: "health check", translation: "verificación de estado", category: "devops" },
  { term: "artifact", translation: "artefacto", category: "devops" },
  { term: "registry", translation: "registro de artefactos", category: "devops" },
  { term: "configuration management", translation: "gestión de configuración", category: "devops" },
  { term: "provisioning", translation: "aprovisionamiento", category: "devops" },
  { term: "service mesh", translation: "malla de servicios", category: "devops" },
  { term: "observability", translation: "observabilidad", category: "devops" },

  // --- database ---
  { term: "query", translation: "consulta", category: "database" },
  { term: "index", translation: "índice", category: "database" },
  { term: "migration", translation: "migración", category: "database" },
  { term: "schema", translation: "esquema", category: "database" },
  { term: "foreign key", translation: "clave foránea", category: "database" },
  { term: "join", translation: "unión (JOIN)", category: "database" },
  { term: "normalization", translation: "normalización", category: "database" },
  { term: "transaction", translation: "transacción", category: "database" },
  { term: "backup", translation: "copia de seguridad", category: "database" },
  { term: "replica", translation: "réplica", category: "database" },
  { term: "shard", translation: "fragmento (shard)", category: "database" },
  { term: "partition", translation: "partición", category: "database" },
  { term: "cursor", translation: "cursor", category: "database" },
  { term: "stored procedure", translation: "procedimiento almacenado", category: "database" },
  { term: "trigger", translation: "disparador", category: "database" },
  { term: "view", translation: "vista", category: "database" },
  { term: "primary key", translation: "clave primaria", category: "database" },
  { term: "table", translation: "tabla", category: "database" },
  { term: "row", translation: "fila", category: "database" },
  { term: "column", translation: "columna", category: "database" },
  { term: "constraint", translation: "restricción", category: "database" },
  { term: "connection pool", translation: "pool de conexiones", category: "database" },
  { term: "deadlock", translation: "interbloqueo", category: "database" },
  { term: "seed data", translation: "datos iniciales", category: "database" },
  { term: "ORM", translation: "ORM (mapeo objeto-relacional)", category: "database" },

  // --- mobile ---
  { term: "responsive design", translation: "diseño responsivo", category: "mobile" },
  { term: "viewport", translation: "ventana gráfica (viewport)", category: "mobile" },
  { term: "breakpoint", translation: "punto de quiebre", category: "mobile" },
  { term: "native app", translation: "aplicación nativa", category: "mobile" },
  { term: "hybrid app", translation: "aplicación híbrida", category: "mobile" },
  { term: "progressive web app", translation: "aplicación web progresiva", category: "mobile" },
  { term: "push notification", translation: "notificación push", category: "mobile" },
  { term: "deep link", translation: "enlace profundo", category: "mobile" },
  { term: "app store", translation: "tienda de aplicaciones", category: "mobile" },
  { term: "simulator", translation: "simulador", category: "mobile" },
  { term: "emulator", translation: "emulador", category: "mobile" },
  { term: "gesture", translation: "gesto", category: "mobile" },
  { term: "touch event", translation: "evento táctil", category: "mobile" },
  { term: "widget", translation: "widget", category: "mobile" },
  { term: "bundle size", translation: "tamaño del paquete", category: "mobile" },
  { term: "hot reload", translation: "recarga en caliente", category: "mobile" },
  { term: "splash screen", translation: "pantalla de inicio", category: "mobile" },
  { term: "onboarding", translation: "incorporación (onboarding)", category: "mobile" },
  { term: "runtime permission", translation: "permiso en tiempo de ejecución", category: "mobile" },
  { term: "biometric authentication", translation: "autenticación biométrica", category: "mobile" },
  { term: "accessibility", translation: "accesibilidad", category: "mobile" },
  { term: "screen reader", translation: "lector de pantalla", category: "mobile" },
  { term: "offline mode", translation: "modo sin conexión", category: "mobile" },
  { term: "API rate limiting", translation: "limitación de tasa de API", category: "mobile" },
  { term: "lazy loading", translation: "carga diferida", category: "mobile" },

  // --- networking ---
  { term: "firewall", translation: "cortafuegos", category: "networking" },
  { term: "VPN", translation: "VPN (red privada virtual)", category: "networking" },
  { term: "DNS", translation: "DNS (sistema de nombres de dominio)", category: "networking" },
  { term: "CDN", translation: "CDN (red de distribución de contenido)", category: "networking" },
  { term: "packet", translation: "paquete", category: "networking" },
  { term: "socket", translation: "socket", category: "networking" },
  { term: "port", translation: "puerto", category: "networking" },
  { term: "TLS", translation: "TLS (seguridad de la capa de transporte)", category: "networking" },
  { term: "proxy", translation: "proxy", category: "networking" },
  { term: "bandwidth", translation: "ancho de banda", category: "networking" },
  { term: "latency", translation: "latencia", category: "networking" },
  { term: "throughput", translation: "rendimiento", category: "networking" },
  { term: "ping", translation: "ping", category: "networking" },
  { term: "traceroute", translation: "traceroute", category: "networking" },
  { term: "subnet", translation: "subred", category: "networking" },
  { term: "IP address", translation: "dirección IP", category: "networking" },
  { term: "MAC address", translation: "dirección MAC", category: "networking" },
  { term: "DHCP", translation: "DHCP (protocolo de configuración dinámica de host)", category: "networking" },
  { term: "HTTP status code", translation: "código de estado HTTP", category: "networking" },
  { term: "SSL certificate", translation: "certificado SSL", category: "networking" },
  { term: "caching", translation: "almacenamiento en caché", category: "networking" },
  { term: "websocket", translation: "websocket", category: "networking" },
  { term: "load testing", translation: "prueba de carga", category: "networking" },
  { term: "DDoS", translation: "DDoS (ataque de denegación de servicio distribuido)", category: "networking" },
  { term: "SSH", translation: "SSH (shell seguro)", category: "networking" },
];

export const GLOSSARY_DATA: GlossaryEntry[] = RAW_GLOSSARY_DATA.map((entry) => ({
  ...SOURCE_BY_CATEGORY[entry.category || "general"],
  confidence: entry.confidence || "medium",
  ...entry,
}));

export function searchGlossary(query: string): GlossaryEntry[] {
  if (!query || query.trim() === "") {
    return [];
  }

  const lowerQuery = query.toLowerCase();

  return GLOSSARY_DATA.filter((entry) =>
    entry.term.toLowerCase().includes(lowerQuery) ||
    entry.translation.toLowerCase().includes(lowerQuery) ||
    entry.category?.toLowerCase().includes(lowerQuery)
  );
}

export function getGlossaryByCategory(category?: string): GlossaryEntry[] {
  if (!category) {
    return GLOSSARY_DATA;
  }

  const lowerCategory = category.toLowerCase();

  return GLOSSARY_DATA.filter((entry) =>
    entry.category?.toLowerCase() === lowerCategory
  );
}
